# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Desktop/project2-burak-yildiz-2015400069

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Desktop/project2-burak-yildiz-2015400069

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/project2-burak-yildiz-2015400069/CMakeFiles /home/student/Desktop/project2-burak-yildiz-2015400069/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/project2-burak-yildiz-2015400069/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project2

# Build rule for target.
project2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project2
.PHONY : project2

# fast build rule for target.
project2/fast:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/build
.PHONY : project2/fast

Barista.o: Barista.cpp.o
.PHONY : Barista.o

# target to build an object file
Barista.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Barista.cpp.o
.PHONY : Barista.cpp.o

Barista.i: Barista.cpp.i
.PHONY : Barista.i

# target to preprocess a source file
Barista.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Barista.cpp.i
.PHONY : Barista.cpp.i

Barista.s: Barista.cpp.s
.PHONY : Barista.s

# target to generate assembly for a file
Barista.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Barista.cpp.s
.PHONY : Barista.cpp.s

Cashier.o: Cashier.cpp.o
.PHONY : Cashier.o

# target to build an object file
Cashier.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cashier.cpp.o
.PHONY : Cashier.cpp.o

Cashier.i: Cashier.cpp.i
.PHONY : Cashier.i

# target to preprocess a source file
Cashier.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cashier.cpp.i
.PHONY : Cashier.cpp.i

Cashier.s: Cashier.cpp.s
.PHONY : Cashier.s

# target to generate assembly for a file
Cashier.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cashier.cpp.s
.PHONY : Cashier.cpp.s

Customer.o: Customer.cpp.o
.PHONY : Customer.o

# target to build an object file
Customer.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.o
.PHONY : Customer.cpp.o

Customer.i: Customer.cpp.i
.PHONY : Customer.i

# target to preprocess a source file
Customer.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.i
.PHONY : Customer.cpp.i

Customer.s: Customer.cpp.s
.PHONY : Customer.s

# target to generate assembly for a file
Customer.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.s
.PHONY : Customer.cpp.s

Employee.o: Employee.cpp.o
.PHONY : Employee.o

# target to build an object file
Employee.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Employee.cpp.o
.PHONY : Employee.cpp.o

Employee.i: Employee.cpp.i
.PHONY : Employee.i

# target to preprocess a source file
Employee.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Employee.cpp.i
.PHONY : Employee.cpp.i

Employee.s: Employee.cpp.s
.PHONY : Employee.s

# target to generate assembly for a file
Employee.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Employee.cpp.s
.PHONY : Employee.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... project2"
	@echo "... rebuild_cache"
	@echo "... Barista.o"
	@echo "... Barista.i"
	@echo "... Barista.s"
	@echo "... Cashier.o"
	@echo "... Cashier.i"
	@echo "... Cashier.s"
	@echo "... Customer.o"
	@echo "... Customer.i"
	@echo "... Customer.s"
	@echo "... Employee.o"
	@echo "... Employee.i"
	@echo "... Employee.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

